name: Run binaries

on:
  workflow_dispatch:
    inputs:
      num1:
        description: num1 in calc
      num2:
        description: num2 in calc
      oper:
        type: choice
        description: operation
        options:
          - "add"
          - "sub"
          - "mult"
          - "div"
  
run-name: calc ${{inputs.oper}} ${{inputs.num1}} and ${{inputs.num2}} run by @${{ github.actor }}

jobs: 
  run-app:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: go-calculator-linux
          path: bin/

      - name: Run binary
        run: |
          chmod +x bin/go-calculator-linux
          ./bin/go-calculator-linux --num1 "${{ inputs.num1 }}" --num2 "${{ inputs.num2 }}" --oper "${{ inputs.oper }}"
